### ISSUE TITLE
Server Fails to Process Fast Commands

### ISSUE THREAD

**Issue by jakedp7** [aribrill/sct-slow-control#2]
I've narrowed down the issue a bit, and it seems that the server is struggling to respond to multiple quick, successive commands. That is, when the GUI sends the set_alerts command and then immediately sends the set_monitoring command, set_alerts never processes on the server. However, if I add a 1-second wait between the two sends, the server properly processes both.

Not sure if this is expected behavior, an artifact of the server implementation, or if there's some piece of processing/command-sending code I'm missing in the GUI. Does it seem reasonable that this is a server issue, or is this more likely on my end?

**Comment by aribrill** [comment]
I'll look into this now. This is not expected behavior. The server as intended should process all received commands without needing sleeps in between, although there is no guaranteed 1-1 correspondence between input and output packets. Are we sure the set_alerts command is actually being sent by the GUI? Do you see this problem with the mock_server, the standard server, or both? In my testing the server code on site, I don't remember seeing this issue, though that doesn't mean there couldn't be a disguised bug that only crops up on some systems.

**Comment by jakedp7** [comment]
Hard to say for sure. I can confirm that the `socket.sendall` is being run from the GUI for each command (set_alerts and set_monitoring), but if I print each command in the main server loop, I only observe the latter.

I'm seeing the issue when I run the mock_server code - but I think the issue itself is manifesting in the server.py code, not the mock_server.py code. Also, I'm seeing the same behavior when I run everything from my windows environment and my Ubuntu VM.

**Comment by aribrill** [comment]
What commands are you sending to the server to generate this bug, and what output do you get? I just ran the following code using the mock server and it executed as I expected. I ran this in the package branch (#3), as that's how I got the mock code running on my machine, but the functionality should be the same.

> (sctcamsoft) aribrill@thinkpad:~/CTA/sctcamsoft$ python sctcamsoft/server.py config.yml commands.yml --mock
> Slow Control Server
> Initializing server...
> Configuring devices:
> Configuring fan...
> Configuring network...
> Configuring power...
> Configuration complete.

> (sctcamsoft) aribrill@thinkpad:~/CTA/sctcamsoft$ python sctcamsoft/user_input.py config.yml commands.yml 
> SCT Slow Control - Input
> Type 'startup' to prepare camera for operation (Operations Manual sec. 5.1 and 5.2). When everything is connected and on, type 'start_HV' to turn on HV, and 'stop_HV' to turn it off. When done taking data, type 'shutdown' to prepare camera for shutdown (Manual sec. 6.1).
> \> startup
> \> start_HV
> 

> (sctcamsoft) aribrill@thinkpad:~/CTA/sctcamsoft$ python sctcamsoft/user_output.py config.yml
> SCT Slow Control - Output
> server: alert_set: fan_connection
> server: alert_set: fan_voltage
> server: alert_set: fan_current
> server: alert_set: eth6_connection
> server: alert_set: eth6_activity
> server: alert_set: eth7_connection
> server: alert_set: eth7_activity
> server: alert_set: eth8_connection
> server: alert_set: eth8_activity
> server: alert_set: eth9_connection
> server: alert_set: eth9_activity
> server: alert_set: power_supply_current
> server: alert_set: HV_current
> fan: current: 15.038
> fan: voltage: 24.564
> power: supply_nominal_voltage: 70.0
> power: supply_measured_voltage: 70.709
> power: supply_current: 2.13
> fan: connected: 1
> fan: voltage: 24.34
> fan: current: 15.871
> network: eth6: 154
> network: eth7: 185
> network: eth8: 261
> network: eth9: 210
> power: supply_current: 2.152
> power: HV_current: -0.013
> ALERT: HV_current: -0.013
> power: supply_current: 2.338
> power: HV_current: 0.003
> power: supply_current: 1.956
> power: HV_current: -0.004
> ALERT: HV_current: -0.004
> power: supply_current: 2.224
> power: HV_current: -0.002
> ALERT: HV_current: -0.002
> power: supply_current: 1.928
> power: HV_current: 0.011
> power: supply_current: 1.877
> power: HV_current: -0.013
> ALERT: HV_current: -0.013
> fan: connected: 1
> fan: voltage: 24.972
> fan: current: 15.399
> network: eth6: 248
> network: eth7: 216
> network: eth8: 208
> network: eth9: 174
> power: supply_current: 2.477
> power: HV_current: -0.0
> power: supply_current: 1.88
> power: HV_current: -0.003
> ALERT: HV_current: -0.003
> power: supply_current: 1.819
> power: HV_current: -0.003
> ALERT: HV_current: -0.003
> power: supply_current: 1.93
> power: HV_current: 0.508
> power: supply_current: 2.002
> power: HV_current: 0.425
> power: supply_current: 1.98
> power: HV_current: 0.491
> network: eth6: 236
> network: eth7: 198
> network: eth8: 269
> network: eth9: 136
> fan: connected: 1
> fan: voltage: 24.407
> fan: current: 15.04
> power: supply_current: 1.904
> power: HV_current: 0.337
> power: supply_current: 1.908
> power: HV_current: 0.577
> power: supply_current: 1.992
> power: HV_current: 0.486
> power: supply_current: 1.969

**Comment by jakedp7** [comment]
I'm actually not using the user_input script - it's two successive requests from the GUI program. The problem doesn't seem to exist when I type the commands in the input terminal (but my guess is that that's because the delay between them is enforced by typing speed). I'll follow up here soon with some more information.

**Comment by jakedp7** [comment]
So, the GUI itself should send three commands as it's starting up: `connect_devices`, `set_alerts`, and `set_monitoring`. In the repo's current state (e2cc9b9), only the first and last are listed at lines 61 and 62 in the gui's main.py file (I removed the `set_alerts` a while ago when it wasn't working). While I'm debugging this, I added `set_alerts` back on my local copy.

These calls use pyqt's thread communication mechanism to talk to the ServerIO thread. Adding print statements after the `socket.sendall` call (in that thread) server confirms that the code is actually being run.

Next, I added `print`s to the server code itself, after line 343 to see if the command is being processed by the server. Even when the GUI sends all three commands, the middle one is usually dropped out, and I just get the following:
```
UserCommand(command='connect_devices', args={})
UserCommand(command='set_monitoring', args={})
```

If I reorder the commands sent, so it's `connect_devices`, `set_monitoring`, and `set_alerts`, the server registers `connect_devices` and `set_alerts`, but usually doesn't catch `set_monitoring`.

Finally, I modified the `user_input.py` script to just send those 3 commands - same thing, only the first and last are printed by the server, unless I add a short wait between each command send. The modified `user_input.py` script is below.
```python
"""Input client for slow control.
Terminal to type in commands, the output of which are displayed
in the output client to prevent blocking.
"""

import argparse
import socket
import shlex

import yaml

import slow_control_pb2 as sc

import time

# Load configuration
parser = argparse.ArgumentParser()
parser.add_argument('config_file', help='Path to slow control config file')
parser.add_argument('commands_file', help='Path to slow control commands file')
args = parser.parse_args()

with open(args.config_file, 'r') as config_file:
    config = yaml.load(config_file)
server_host = config['user_interface']['host']
server_port = config['user_interface']['input_port']

# Open a socket to the slow control server
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((server_host, server_port))

with open(args.commands_file, 'r') as commands_file:
    commands = yaml.load(commands_file)

# Return a serialized message containing the UserCommand corresponding
# to the input entered by the user. If the command isn't valid, return None.
def parse_and_serialize_user_input(raw_user_input):
    raw_user_input = shlex.split(raw_user_input.strip())
    command = raw_user_input[0]
    user_input = raw_user_input[1:]
    if command not in commands:
        raise ValueError("command '{}' not recognized".format(command))
    args = commands[command].get('args', {})
    unspecified_args = [a for a in args if args[a] is None 
            or isinstance(a, dict) and args[a].get('value') is None]
    if len(user_input) == len(args):
        user_args = args
    elif len(user_input) == len(unspecified_args):
        user_args = unspecified_args
    else:
        raise IndexError("command '{}' requires {} arguments, {} given".format(
            command, len(args), len(user_input)))
    message = sc.UserCommand()
    message.command = command
    for user_arg, input_value in zip(user_args, user_input):
        message.args[user_arg] = input_value
    return message.SerializeToString()

def send_cmd(cmd):
    serialized_command = parse_and_serialize_user_input(cmd)
    sock.sendall(serialized_command)

try:
    send_cmd('connect_devices')
    # time.sleep(0.5)
    send_cmd('set_alerts')
    # time.sleep(0.5)
    send_cmd('set_monitoring')

except (ValueError, IndexError) as e:
    print(e)
```

Quick note: everything I just mentioned is with the most recent code and the mock server.
