### ISSUE TITLE
Combine user communication functions between command line and GUI code

### ISSUE THREAD

**Issue by aribrill** [aribrill/sct-slow-control#5]
As mentioned in #4, the socket communication functions between the user and server are duplicated between the command line and GUI code. For ease of future maintenance, these should be combined. If we decide it's worth it to maintain text-based code indefinitely, user communication could be made into common functions to be imported by both sets of code. If not, the other option is to just delete the command-line code.

**Comment by jakedp7** [comment]
While maybe not necessary, I think maintaining the terminal interface is certainly valuable. We could either expose some of the functions in `user_input` and `user_output`, or create an entirely separate class. I'd probably prefer the latter, if that's ok with you. If we go that route, should input and output functionality fall into the same class?

**Comment by jakedp7** [comment]
@aribrill Just wanted to offer up my help on this one - if you're busy, I'm happy to take it!

**Comment by aribrill** [comment]
By all means, please go for it!
